In [2]:
import numpy as np

## creating arrays
## 1D Array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [17]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5))
# arr2.reshape((1,4)) --> will give error as array of 5 columns cannot be reshaped to 4 columns
arr3 = arr2.reshape((5,1))

print(f"array with 5 rows and 1 column {arr3}")
print(f"array with 1 rows and 5 column {arr2}")

array with 5 rows and 1 column [[1]
 [2]
 [3]
 [4]
 [5]]
array with 1 rows and 5 column [1 2 3 4 5]


In [18]:
## 2D array

arr4 = np.array([[1,2,3,4,5], [3,4,5,6,7]])
print(arr4)
print(arr4.shape)

[[1 2 3 4 5]
 [3 4 5 6 7]]
(2, 5)


In [20]:
np.arange(0,10,2) # np.arange(start_position_inclusive, end_position_excluding, step_size)

array([0, 2, 4, 6, 8])

In [22]:
np.ones((3,4)) ## 2D array with 3 rows and 4 columns with all elements as 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
## Numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## element wise addition
print("addition: " , arr1 + arr2)

## element wise substraction
print("substraction: ", arr1 - arr2)

## element wise mult
print("mult: ", arr1 * arr2)

## element wise div
print("div: ", arr2/arr1)


addition:  [11 22 33 44 55]
substraction:  [ -9 -18 -27 -36 -45]
mult:  [ 10  40  90 160 250]
div:  [10. 10. 10. 10. 10.]


In [27]:
## Universal functions

arr = np.array([2,3,4,5,6])

print(np.sqrt(arr))

# exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

# log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [31]:
## Array slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [12,243,45,67]])
print("array: \n", arr)
print("first element: ", arr[0][0])
print("last element: ", arr[2][3])

array: 
 [[  1   2   3   4]
 [  5   6   7   8]
 [ 12 243  45  67]]
first element:  1
last element:  67


In [32]:
arr[1:]

array([[  5,   6,   7,   8],
       [ 12, 243,  45,  67]])

In [35]:
arr[1:, 2:]

array([[ 7,  8],
       [45, 67]])

In [42]:
arr[0:, 1:]

array([[  2,   3,   4],
       [  6,   7,   8],
       [243,  45,  67]])

In [43]:
arr[1:] = 100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [45]:
## Statistical concept -- Normalization

data = np.array([1,2,45,6,7])

mean = np.mean(arr)
std_dev = np.std(data)
variance = np.var(data)

print("mean is: ", mean)
print("standard deviation: ", std_dev)
print("variance is: ", variance)

normalized_data = (data-mean)/std_dev
print("normalized data: ", normalized_data)

mean is:  67.5
standard deviation:  16.557777628655362
variance is:  274.15999999999997
normalized data:  [-4.01623947 -3.95584489 -1.35887802 -3.71426657 -3.653872  ]


In [55]:
## Logical operation

data = np.array([1,2,3,4,5,6,7,87])

print(data[(data>5) & (data<8)])
print(data[(data>5) | (data<8)])

[6 7]
[ 1  2  3  4  5  6  7 87]
