# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [6]:
## Ass1-1
import numpy as np

arr = np.random.randint(1,21, size=(5,5))
print("random array of 5X5: \n", arr)

## manipulation
arr[:, 2] = 1
print("manipulated array: \n", arr)

random array of 5X5: 
 [[11 14  8 11 11]
 [ 2 12 20  1 15]
 [ 5  5 19  1  3]
 [ 5  4 12  6 19]
 [ 5 18 17  9  7]]
manipulated array: 
 [[11 14  1 11 11]
 [ 2 12  1  1 15]
 [ 5  5  1  1  3]
 [ 5  4  1  6 19]
 [ 5 18  1  9  7]]


In [9]:
## Ass1-2

arr = np.random.randint(1, 17, size=(4,4))
print("random array of 5X5: \n", arr)

np.fill_diagonal(arr, 0)
print("manipulated array: \n", arr)

random array of 5X5: 
 [[ 1  1  1  8]
 [ 2  9  6  4]
 [10  9 15 16]
 [ 4 16 16  2]]
manipulated array: 
 [[ 0  1  1  8]
 [ 2  0  6  4]
 [10  9  0 16]
 [ 4 16 16  0]]


In [12]:
## Ass2-1 Array extraction

arr = np.random.randint(1, 37, size=(6,6))
print("random array of 5X5: \n", arr)

extracted_array = arr[2:5, 1:4]
print("extracted array: \n", extracted_array)


random array of 5X5: 
 [[ 2 21 24 21 32 25]
 [23 12 11  1  6 14]
 [ 3  6  9  4 21 20]
 [ 5 26 14 25 20 20]
 [ 6 12 30 31 25 20]
 [22 36  4 16 29  2]]
extracted array: 
 [[ 6  9  4]
 [26 14 25]
 [12 30 31]]


In [16]:

# Create a 5x5 array with random integers
np.random.seed(0)  # For reproducibility
arr = np.random.randint(1, 21, size=(5, 5))

print("Original array:")
print(arr)

# Extract the elements on the border
top_row = arr[0, :]
bottom_row = arr[-1, :]
left_col = arr[1:-1, 0]
right_col = arr[1:-1, -1]

border_elements = np.concatenate((top_row, right_col, bottom_row[::-1], left_col[::-1]))

print("\nBorder elements:")
print(border_elements)

Original array:
[[13 16  1  4  4]
 [ 8 10 20 19  5]
 [ 7 13  2  7  8]
 [15 18  6 14  9]
 [10 20 17 20  6]]

Border elements:
[13 16  1  4  4  5  8  9  6 20 17 20 10 15  7  8]


In [19]:
## Ass3-1

arr = np.random.randint(1, 31, size=(4,4))
print("Original array: \n", arr)

row_sum = np.sum(arr, axis=1)
print("row sum: ", row_sum)
col_sum = np.sum(arr, axis=0)
print("column sum: ", col_sum)

Original array: 
 [[26  1 11 21]
 [24  4 12 19]
 [24 29  3  1]
 [ 1  5 22  6]]
row sum:  [59 59 57 34]
column sum:  [75 39 48 47]
