# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2.  

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
## Ass1-1
import numpy as np

arr = np.random.randint(1,21, size=(5,5))
print("random array of 5X5: \n", arr)

## manipulation
arr[:, 2] = 1
print("manipulated array: \n", arr)

random array of 5X5: 
 [[18  6 12  8 13]
 [10 10  8 10  6]
 [15  8  4  5 12]
 [ 2 13  9 19 10]
 [ 7  2  1  4  6]]
manipulated array: 
 [[18  6  1  8 13]
 [10 10  1 10  6]
 [15  8  1  5 12]
 [ 2 13  1 19 10]
 [ 7  2  1  4  6]]


In [4]:
## Ass1-2

arr = np.random.randint(1, 17, size=(4,4))
print("random array of 5X5: \n", arr)

np.fill_diagonal(arr, 0)
print("manipulated array: \n", arr)

random array of 5X5: 
 [[ 3 15 10 13]
 [14  2 13  1]
 [ 4  2 13  6]
 [ 7  6  7 16]]
manipulated array: 
 [[ 0 15 10 13]
 [14  0 13  1]
 [ 4  2  0  6]
 [ 7  6  7  0]]


In [5]:
## Ass2-1 Array extraction

arr = np.random.randint(1, 37, size=(6,6))
print("random array of 5X5: \n", arr)

extracted_array = arr[2:5, 1:4]
print("extracted array: \n", extracted_array)


random array of 5X5: 
 [[16 28 33  5  6 17]
 [22 28  5  6 28 31]
 [ 3 14 17  5 28 27]
 [30 34 23 26 34 25]
 [20  8 12 18 31 36]
 [17 10 21 35 26 25]]
extracted array: 
 [[14 17  5]
 [34 23 26]
 [ 8 12 18]]


In [6]:

# Create a 5x5 array with random integers
np.random.seed(0)  # For reproducibility
arr = np.random.randint(1, 21, size=(5, 5))

print("Original array:")
print(arr)

# Extract the elements on the border
top_row = arr[0, :]
bottom_row = arr[-1, :]
left_col = arr[1:-1, 0]
right_col = arr[1:-1, -1]

border_elements = np.concatenate((top_row, right_col, bottom_row[::-1], left_col[::-1]))

print("\nBorder elements:")
print(border_elements)

Original array:
[[13 16  1  4  4]
 [ 8 10 20 19  5]
 [ 7 13  2  7  8]
 [15 18  6 14  9]
 [10 20 17 20  6]]

Border elements:
[13 16  1  4  4  5  8  9  6 20 17 20 10 15  7  8]


In [7]:
## Ass3-1

arr = np.random.randint(1, 31, size=(4,4))
print("Original array: \n", arr)

row_sum = np.sum(arr, axis=1)
print("row sum: ", row_sum)
col_sum = np.sum(arr, axis=0)
print("column sum: ", col_sum)

Original array: 
 [[16 16  1 19]
 [ 4 25 18 20]
 [30 20 20 15]
 [ 8  1  2 10]]
row sum:  [52 67 85 21]
column sum:  [58 62 41 64]


In [8]:
## Ass4-1
from scipy import stats

arr = np.random.randint(1,100, size=(5,5))
print("Original array: \n", arr)

new_arr = arr.flatten()
print("flattened array: ", new_arr)

print("mean: ", np.mean(new_arr))
print("median: ", np.median(new_arr))
print("mode: ", stats.mode(new_arr))
print("standard deviation: ", np.std(new_arr))
print("variance: ", np.var(new_arr))

Original array: 
 [[58 33 32 75 24]
 [36 76 56 29 35]
 [ 1  1 37 54  6]
 [39 18 80  5 43]
 [59 32  2 66 42]]
flattened array:  [58 33 32 75 24 36 76 56 29 35  1  1 37 54  6 39 18 80  5 43 59 32  2 66
 42]
mean:  37.56
median:  36.0
mode:  ModeResult(mode=np.int32(1), count=np.int64(2))
standard deviation:  23.455626190745793
variance:  550.1664


In [16]:
## Ass4-2

# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape(3, 3)
print("Original array:")
print(array)

# Normalize the array
mean = array.mean()
std_dev = array.std()
normalized_array = (array - mean) / std_dev
print("\nNormalized array:")
print(normalized_array)

# Verify the normalization
print("\nMean of normalized array:", normalized_array.mean())
print("Standard deviation of normalized array:", normalized_array.std())

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]

Mean of normalized array: 0.0
Standard deviation of normalized array: 1.0


In [19]:
## Ass5-1

arr = np.random.randint(1,11, size=(3,3))
arr2 = np.random.randint(1,11, size=(3,))

print("Original array: \n", arr)
print("second array: \n", arr2)

final_arr = arr + arr2
print("final array: \n", final_arr)

Original array: 
 [[7 4 4]
 [9 9 9]
 [3 4 3]]
second array: 
 [1 9 9]
final array: 
 [[ 8 13 13]
 [10 18 18]
 [ 4 13 12]]


In [6]:
## As5-2
arr = np.random.randint(1,11, size=(4,4))
arr2 = np.random.randint(1,11, size=(4,))

print("Original array: \n", arr)
print("second array: \n", arr2)

# We need to add a new axis to arr_1d to enable broadcasting

final_arr = arr-arr2[:, np.newaxis]
print("final array: \n", final_arr)

Original array: 
 [[10  5  4 10]
 [ 2 10  5  3]
 [ 1  8 10  6]
 [ 4  7  5  2]]
second array: 
 [ 7 10  3  4]
final array: 
 [[ 3 -2 -3  3]
 [-8  0 -5 -7]
 [-2  5  7  3]
 [ 0  3  1 -2]]


In [10]:
## Ass6-1

arr = np.random.randint(1,11, size=(3,3))
print("Original array: \n", arr)

determinant = np.linalg.det(arr)
print("determinant: ", determinant)

inverse = np.linalg.inv(arr)
print("Inverse of array: ", inverse)

eigen_val =  np.linalg.eig(arr)
# print("eigen value: ", eigen_val)    -> returns an object of eigen values and eigen vectors 
print(eigen_val.eigenvalues)       

Original array: 
 [[ 3  6 10]
 [10  7  3]
 [ 5  1 10]]
determinant:  -559.0
Inverse of array:  [[-0.11985689  0.08944544  0.09302326]
 [ 0.15205725  0.03577818 -0.1627907 ]
 [ 0.04472272 -0.04830054  0.06976744]]
[-4.60650763 17.78230385  6.82420377]


In [11]:
## Ass6-2

arr1 = np.random.randint(1,11, size=(3,4))
arr2 = np.random.randint(1,11, size=(4,3))

final_arr = np.linalg.matmul(arr1, arr2)
print(final_arr)

[[ 87  77 120]
 [ 73  60  82]
 [ 76  64  54]]
